# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1024
CPU = 1
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: IP
  config.vm.provision "ansible_local" do |ans|
    ans.playbook = "nginx.yml"
    ans.install = true
    ans.install_mode = "pip"
    ans.pip_install_cmd = "curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | sudo python"
  end
end