name: workflow-master
on:
  push:
    branches:
      - "main"
jobs:
  job-master:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1

    - name: "step-log"
      run: |
        echo "[B] github.ref: ${{github.ref}}"
