# -*- mode: ruby -*-
# vi: set ft=ruby :

IPlb = "10.0.0.10"
IPweb1 = "10.0.0.11"
IPweb2 = "10.0.0.12"
RAM = 1024
CPU = 1

Vagrant.configure("2") do |config|

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
    lb.vm.network "private_network", ip: IPlb
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
    web1.vm.network "private_network", ip: IPweb1
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
    web2.vm.network "private_network", ip: IPweb2
  end
end
